### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by VINEET-KAUSHIK** [benmarwick/AAA2011-Tweets#2]
The codes are very helpful. But I stuck in between.
I have collected data from Twitter "rtweet" and used "tm" package to make a document term matrix, further I am using "topicmodels" package to make themes out of the data I have collected 
>ldadone<-LDA(tdm, k=5, method = "Gibbs", control = NULL, model = NULL)
>topics(ldadone)#it will show topics frequency
>ldadone.topics <- as.matrix(topics(ldadone))

I have run the codes till here, but how to proceed further. Please suggest, or refer some link!!
Your classic code of 2013 is very helpful!! but I want to learn as how to find the topics from the collected tweets...

**Comment by benmarwick** [comment]
Hello, @VINEET-KAUSHIK I suggest you post your question to https://stackoverflow.com/m and include a small fully working reproducible example. You are welcome to post the link to your question in this thread so we can follow up.
